Repository Interacao-Humano-Computador/2020.1-CD-MOJ, pull requests merged in 2020-09, with the labels that each got.

#2 Criação wiki do projeto
  docs/index.md
  mkdocs.yml
Labels: nova feature

#5 Melhoria no pages
  README.md
  docs/assets/icons/computer_black.png
  docs/assets/icons/computer_white.png
  docs/assets/integrantes/Igor.png
  docs/assets/integrantes/Marcelo.png
  docs/assets/integrantes/Rhuan.png
  docs/assets/integrantes/ThiagoG.png
  docs/assets/integrantes/ThiagoL.png
  docs/index.md
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: enhancement

#6 Criação documento de planejamento
  docs/assets/logos/Discord.png
  docs/assets/logos/Docs.png
  docs/assets/logos/GitHub.png
  docs/assets/logos/Lucidchart.png
  docs/assets/logos/Office365.png
  docs/assets/logos/Overleaf.png
  docs/assets/logos/Telegram.png
  docs/assets/logos/ZenHub.png
  docs/assets/tabela_horarios/tabela_horarios.jpg
  docs/assets/tabela_horarios/tabela_horarios_legenda1.jpg
  docs/assets/tabela_horarios/tabela_horarios_legenda2.jpg
  docs/planejamento.md
Labels: documentation, nova feature

#8 Adição aba de apresentações
  docs/apresentacoes.md
  mkdocs.yml
Labels: documentation, nova feature
