Repository Interacao-Humano-Computador/2020.1-CD-MOJ, pull requests merged in 2020-11, with the labels that each got.

#29 Correção link na avaliação do storyboard
  docs/DeAD/nivel1/avaliacao_storyboard.md
Labels: melhorias

#30 Segundo nível do ciclo de Mayhew
  docs/DeAD/nivel2/planejamento_avaliacao_media.md
  docs/DeAD/nivel2/prototipo_media_fidelidade.md
  docs/DeAD/nivel2/sketch.md
  docs/assets/media_fidelidade/FAQ.png
  docs/assets/media_fidelidade/contest.png
  docs/assets/media_fidelidade/contests.png
  docs/assets/media_fidelidade/home.png
  docs/assets/media_fidelidade/novidades.png
  docs/assets/media_fidelidade/questao.png
  docs/assets/media_fidelidade/questao_estado_02.png
  docs/assets/media_fidelidade/questao_estado_03.png
  docs/assets/media_fidelidade/scoreboard.png
  docs/assets/media_fidelidade/sobre.png
  docs/assets/sketches/FAQ.png
  docs/assets/sketches/about_us.png
  docs/assets/sketches/collapsable.png
  docs/assets/sketches/contest.png
  docs/assets/sketches/contests.png
  docs/assets/sketches/home.png
  docs/assets/sketches/noticias.png
  docs/assets/sketches/scoreboard.png
  docs/assets/sketches/visualizar_questao.png
  docs/assets/sketches/visualizar_questao_submeter.png
  docs/assets/sketches/zero_contests.png
  mkdocs.yml
Labels: documentação, melhorias

#32 Protótipo de alta fidelidade
  docs/DeAD/nivel3/prototipo_alta.md
  docs/assets/alta_fidelidade/FAQ.png
  docs/assets/alta_fidelidade/contest.png
  docs/assets/alta_fidelidade/contest_info.png
  docs/assets/alta_fidelidade/contest_tooltip.png
  docs/assets/alta_fidelidade/contests_logado.png
  docs/assets/alta_fidelidade/contests_logado_dropdown_contests.png
  docs/assets/alta_fidelidade/home(contests).png
  docs/assets/alta_fidelidade/home_dropdown_classificar.png
  docs/assets/alta_fidelidade/login.png
  docs/assets/alta_fidelidade/novidades.png
  docs/assets/alta_fidelidade/questao.png
  docs/assets/alta_fidelidade/questao_estado2.png
  docs/assets/alta_fidelidade/questao_estado3.png
  docs/assets/alta_fidelidade/scoreboard.png
  docs/assets/alta_fidelidade/scoreboard_info.png
  docs/assets/alta_fidelidade/sobre.png
  mkdocs.yml
Labels: documentação

#33 Planejamento da avaliação do protótipo de alta fidelidade
  docs/DeAD/nivel2/prototipo_media_fidelidade.md
  docs/DeAD/nivel3/avaliacao/planejamento.md
  docs/DeAD/nivel3/prototipo_alta.md
  docs/apresentacoes.md
  mkdocs.yml
Labels: documentação, melhorias

#34 Adição do documento de preparação para o Teste de Usabilidade
  docs/DeAD/nivel3/avaliacao/planejamento.md
  docs/DeAD/nivel3/avaliacao/prep_teste_usabilidade.md
  docs/DeAD/nivel3/prototipo_alta.md
  mkdocs.yml
Labels: documentação

#35 Relato dos resultados da avaliação do protótipo de alta fidadelidade
  docs/DeAD/nivel3/avaliacao/avaliacao_heuristica.md
  docs/DeAD/nivel3/avaliacao/planejamento.md
  docs/DeAD/nivel3/avaliacao/prep_teste_usabilidade.md
  docs/DeAD/nivel3/avaliacao/relato_geral.md
  docs/DeAD/nivel3/avaliacao/teste_usabilidade.md
  docs/DeAD/nivel3/prototipo_alta.md
  docs/assets/alta_fidelidade/contest.png
  docs/assets/alta_fidelidade/contest_info.png
  docs/assets/alta_fidelidade/contest_tooltip.png
  docs/assets/alta_fidelidade/contests_logado.png
  docs/assets/alta_fidelidade/contests_logado_dropdown_contests.png
  docs/assets/alta_fidelidade/home.png
  docs/assets/alta_fidelidade/meus_contests.png
  docs/assets/alta_fidelidade/meus_contests_dropdown.png
  docs/assets/alta_fidelidade/questao.png
  docs/assets/alta_fidelidade/questao_envio_aprovado.png
  docs/assets/alta_fidelidade/questao_estado2.png
  docs/assets/alta_fidelidade/questao_estado3.png
  docs/assets/alta_fidelidade/questao_estado4.png
  docs/assets/alta_fidelidade/scoreboard.png
  docs/assets/alta_fidelidade/scoreboard_info.png
  docs/planejamento.md
  mkdocs.yml
Labels: documentação, melhorias

#36 Verificação dos artefatos
  docs/DeAD/nivel1/reestruturacao_tarefas.md
  docs/DeAD/nivel2/prototipo_media_fidelidade.md
  docs/DeAD/nivel3/prototipo_alta.md
  docs/analise/validacao_informal.md
  docs/analise/verificacao/guia_de_estilo.md
  docs/analise/verificacao/meta_de_usabilidade.md
  docs/analise/verificacao/personas.md
  docs/analise/verificacao/planejamento.md
  docs/analise/verificacao/prototipo_alta_fidelidade.md
  docs/analise/verificacao/prototipo_media_fidelidade.md
  docs/analise/verificacao/reengenharia.md
  docs/analise/verificacao/sketch.md
  docs/analise/verificacao/storyboard.md
  docs/analise_requisitos/guia_estilo.md
  docs/analise_requisitos/metas_de_usabilidade.md
  mkdocs.yml
Labels: documentação
