Repository Interacao-Humano-Computador/2020.1-CD-MOJ, pull requests merged in 2020-10, with the labels that each got.

#11 Adicionando as personas do projeto
  docs/assets/personas/Breno.jpg
  docs/assets/personas/Lara.jpg
  docs/assets/personas/Maria.jpg
  docs/assets/personas/Samuel.png
  docs/personas.md
  mkdocs.yml
Labels: documentation

#10 Adição da ata de reunião do dia 30/09/2020
  docs/atas/reuniao-30-09-2020.md
  mkdocs.yml
Labels: documentation

#13 Correções nos links das imagens
  docs/personas.md
Labels: bug

#16 Mudança dos links das apresentações para o youtube
  docs/apresentacoes.md
Labels: enhancement

#14 Removendo dados redundantes sobre as personas
  docs/personas.md
Labels: bug

#15 Criação documento de análise hierárquica de tarefas
  docs/analise_tarefas.md
  docs/assets/HTA/analise_tarefas_aluno.png
  docs/assets/HTA/analise_tarefas_professor.png
  mkdocs.yml
Labels: documentation

#17 Criação do documento GOMS
  docs/goms.md
  mkdocs.yml
Labels: documentation

#19 Adição das apresentações na plataforma do youtube
  docs/apresentacoes.md
Labels: documentação, melhorias

#18 Correção documentos de análise de tarefas
  docs/analise_tarefas/goms.md
  docs/analise_tarefas/hta.md
  docs/assets/HTA/analise_tarefas_aluno.png
  docs/assets/HTA/analise_tarefas_professor.png
  mkdocs.yml
Labels: melhorias

#20 Análise de requisitos
  docs/analise_requisitos/caracteristicas.md
  docs/analise_requisitos/guia_estilo.md
  docs/analise_requisitos/metas_de_usabilidade.md
  docs/analise_requisitos/principios.md
  docs/assets/guia_estilo/colors.jpeg
  docs/assets/guia_estilo/font_examples.png
  mkdocs.yml
Labels: documentação

#22 adicionando ata do dia 19/10/2020
  docs/atas/reuniao-19-10-2020.md
  mkdocs.yml
Labels: documentação

#23 Adição do documento de reengenharia do HTA
  docs/DeAD/reestruturacao_tarefas.md
  docs/analise_requisitos/analise_tarefas/hta.md
  docs/assets/HTA/analise_tarefas_aluno_reestruturado.png
  docs/assets/HTA/analise_tarefas_professor_reestruturado.png
  mkdocs.yml
Labels: documentação

#25 Refatoração no documento de planejamento
  docs/assets/logos/LiveShare.png
  docs/assets/logos/Sheets.png
  docs/assets/logos/Slides.png
  docs/assets/logos/Teams.png
  docs/assets/logos/VisualStudioCode.png
  docs/planejamento.md
Labels: melhorias

#24 Storyboards
  docs/DeAD/storyboard.md
  docs/assets/storyboard/aluno_accepted.png
  docs/assets/storyboard/aluno_scoreboard.png
  docs/assets/storyboard/aluno_tle.png
  docs/assets/storyboard/prof_contest.png
  docs/assets/storyboard/prof_scoreboard.png
  docs/assets/storyboard/prof_sherlock.png
  docs/assets/storyboard/prof_statistics.png
  docs/assets/storyboard/prof_subs.png
  mkdocs.yml
Labels: documentação

#27 Adição quarta apresentação
  docs/apresentacoes.md
Labels: documentação
